### ISSUE TITLE
사파리에서 보면 에디터 하단에 로드되지 않는 플래시가..

### ISSUE THREAD

**Issue by kssa** [kakao/DaumEditor#109]
안녕하세요. ^^

에디터 샘플 페이지에서도 마찬가지인데요... 

샘플버튼 바로 밑에 플래시가 있나요~?

다른 브라우저에서는 나오지 않는 문제구요.  사파리에서만 하단에 영역이 잡혀 나와서요. 

샘플페이지에선 같은 흰 배경이라 안보이고 오른쪽 마우스 클릭해서 찾으셔야 될 거예요 ... ㅋㅋ

아이프레임으로 에디터를 넣을 때, 그 로드되지 않은 플래시 영역이 떡하니 밖으로 나와 다른 것들을 가려버려서 알게됐어요~

z-index를 써도 밖으로 나와 있네요. 

사파리가 잘 쓰이진 않지만 그래도 나중에라도 해결이 되었으면 좋겠네요 ^^

**Comment by sskras** [comment]
Hello @kssa , I would like to contact you directly, but I see no way. 
Can you contact me back, please?
