### ISSUE TITLE
멀티 에디터 관련...질문입니다.

### ISSUE THREAD

**Issue by judeoh** [kakao/DaumEditor#249]
ㅡㅡㆀ
질문 드립니다.

다음 에디터를 이용해서 한 페이지에 4개의 에디터를 붙혀야 하는데...

ie에서(ie10) 

SCRIPT5022: failed to initialize editor. caused by Error: [Exception]Trex.Form : not exist element - tx_editor_form2 

이런 메세지가 나오네요..

현재 상황은 에디터 1개만 붙혀놓은 상태이고
소스는  이곳에 있는 샘플 그대로 사용했습니다(http://uie.daum.net/openeditor/sample/latest/editor_multi_sample.html )

form이름 및 id들 모두 완전 동일하게 했습니다..

tx_editor_form2 이란 element가 없다는 예긴데..뭐가 문제일까요?

소스내용을 간략히 적어보면

```
<form name="tx_editor_form2" id="tx_editor_form2" action="http://posttestserver.com/post.php" method="post" accept-charset="utf-8">
......
</form>
</div>
<script type="text/javascript">
var config2 = {
.......
</script>
<script type="text/javascript">
EditorJSLoader.ready(function (Editor) {
             new Editor(config2);
             Editor.getCanvas().observeJob(Trex.Ev.__IFRAME_LOAD_COMPLETE, function() {
                      Editor.modify({
                                              content: 'Editor2'
                                            }); 
                      });
              });
        </script>
      </div>
```

다음에디터는 최신버전  7.3.36 입니다.
쏘스상에서 빠진 내용이 있는지...
분명히 위 데모버전에선 정상적인것 같은데...이상하네요..

**Comment by kanokun** [comment]
어.. 같은 증상이라서 제 소스를 쭉 보다가 문제점을 발견했는데요.
제 경우 바보같이 form 안에 또 form 을 써서 저런 에러가 뜨더라구요.
한참 지난 글이지만 같은 현상으로 고생하실 분이 계실까 남겨둡니다.
