### ISSUE TITLE
데모페이지가 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by cielo** [kakao/DaumEditor#32]
다음에디터를 곧바로 사용해볼 수 있는 데모페이지가 있었으면 좋겠습니다.

**Comment by misol** [comment]
@ragiragi 지금도 위키 링크는 깨진 것 같습니다. 버전 부분에 latest 라고 되어 있는데 나오지 않네요

**Comment by k10526** [comment]
수정 하였습니다.

**Comment by misol** [comment]
감사합니다!

2015년 1월 21일 수요일, youall<notifications@github.com>님이 작성한 메시지:
