### ISSUE TITLE
이미지 및 파일 첨부 문의드립니다.

### ISSUE THREAD

**Issue by heiliglied** [kakao/DaumEditor#460]
게시판을 여러개 쓰기 위해 이미지 업로드 경로를 서버에서 여러군데로 지정하려고 합니다.
1번 게시판에서는 1번 폴더에 이미지 업로드, 2번 게시판에서는 2번 폴더에 업로드... 이런식으로 하나의 에디터로 여러개를 구현하려고 하는데, editor.html 파일에 이미지 업로드 버튼의 id값 tx_image로 제어하는 방법을 알 수가 없어서 문의 드립니다.
저 tx_image 버튼으로 image.html을 호출할 때 파라미터를 같이 보내서 어느 게시판에서 호출했는지를 지정해서 업로드시 파일 업로드 경로를 분기하려고 하는데, 저 호출 이벤트가 어디서 일어나는건지 알고싶습니다.

**Comment by k10526** [comment]
config설정을 통해 popupPageurl을 변경할수 있습니다.
sidebar -> attacher-> file -> popPageUrl
