### ISSUE TITLE
다음에디터 사용시 나타는 증상들 문의 드립니다. 

### ISSUE THREAD

**Issue by simwoo** [kakao/DaumEditor#489]
daumeditor-7.5.11 사용을 최근에 적용하여 사용하고 있습니다. 
이때 나타나는 증상 몇가지 문의 드리고자 합니다. 
V7.4(안정화된 버전) 과 V7.5(개발버전)으로 알고 있어서 처음에는 V7.4최신 버전으로 적용해보았으나 한글작성에 대한 부분이 적용 되지 않아 V7.5로 적용하여 사용해 보았으나 아래와 같은 증상들이 나타났습니다. ㅠ.ㅠ 
1. 크롬브라우저(44.0.2403.155 m) VS 인터넷 익스플로러(11.0.9600.17959, 10)
한글로 작성한 문서를 에디터에 복사 하여 붙여넣을때 클립보드 붙여넣기(MODE_HTML)을 기본으로 익스플로러에서는 글이 사라지는 현상등을 해결하였으나 크롬브라우저에서는 여전히 같은 증상이 발견되었습니다. 
2. 한글 작성한 표를 붙여넣기 하면 border: 0pt 이 되버리는 현상이 나타납니다. 익스플로러와 크롬 동일 증상 

바쁘실텐데 부탁드리겠습니다.

**Comment by k10526** [comment]
크롬, ie 두 브라우져가 클립보드 구현이 다른형태로 구현되어 있습니다. 따라서 해당 이슈는 수정하기 어렵습니다.
