### ISSUE TITLE
윈도7 > IE 11에서 에디터 글 등록 후 다시 수정모드로 들어가면 줄바꿈 들이 사라집니다.

### ISSUE THREAD

**Issue by p4khys** [kakao/DaumEditor#495]
윈도7 > IE 11에서도 동일하게 나타나는거같아요.

이슈들 훑어보니까 몇몇 그런 케이스들이 있는데요. 

예를 들어..
"
A
B
C

D
E

F
"

이런식으로 등록하면 처음 한번은 제대로 보여지는데

게시글을 수정하려고 들어갈 경우.

중간에 엔터쳤던 영역들이 사라져서

"
A
B
C
D
E
F
"
로 나오고 있습니다.

참고로. 
IE11에서 등록된 게시글에서는 타브라우저(구글 크롬이나.. 기타등등)에서, 수정해도 계속 그런 현상이 보이고
IE 외에서 등록한 정상적인 케이스의 게시글에서는 타브라우저(구글 크롬 등등)에서, 계속 수정해도 그런 현상이 발생하지 않습니다.

다 그런게 아니라 특정 브라우저에서만 발생을 하고 있습니다.
맥 > 구글크롬에서는 괜찮은데요.. 어느 부분을 체크해줘 야 하는지 잘 모르겠습니다.

에디터 수정시..
<p><br></p>
에서 
<p></p> 로 변환이 되서 나타나는데요.

어느 부분을 확인 / 수정해야하는지,
혹시 비교해볼 수 있는 url 이 있는지... 확인 부탁드립니다.

**Comment by k10526** [comment]
element로 넣지 마시고 string으로 값을 넣어주시면 됩니다.
