### ISSUE TITLE
한페이지 안에 다음에디터를 2개 호출은 못하나요?

### ISSUE THREAD

**Issue by JungYunMin** [kakao/DaumEditor#58]
한페이지 안에 다음에디터를 2개 호출은 못하나요? 
a.html에서 2개의 에디터를 호출을 할려고 하는데 방법이 없을까요?

**Comment by WickedMISO** [comment]
방법을 찾다가 들어옵니다. 
http://uie.daum.net/openeditor/sample/7.2.6/editor_multi_sample.html
라고 적힌 페이지 접속이 지금 안되는데 설명 좀 부탁드립니다.
